# Generated by Django 4.1.1 on 2022-09-24 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rule_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
