# Generated by Django 4.1.1 on 2022-09-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_task_project_delete_project_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(max_length=9),
        ),
    ]
