# Generated by Django 5.0.4 on 2024-04-28 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_movuser_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('campo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadOrganica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='movuser_product',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='movuser_product',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rule',
        ),
        migrations.CreateModel(
            name='DetalleSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedentes', models.CharField(max_length=200)),
                ('analisis', models.CharField(max_length=1000)),
                ('conclusiones', models.CharField(max_length=300)),
                ('recomendaciones', models.CharField(max_length=200)),
                ('asunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.asunto')),
            ],
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordenCompra', models.IntegerField()),
                ('proveedor', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('serie', models.CharField(max_length=20)),
                ('fechaVenGarantia', models.CharField(max_length=20)),
                ('componentes', models.CharField(max_length=50)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.estado')),
                ('tipo_bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tipo_bien')),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaIngreso', models.CharField(max_length=20)),
                ('fechaEliminacion', models.CharField(max_length=20)),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.movimiento')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UsuarioInicial', models.CharField(max_length=20)),
                ('unidadOrganicaInicial', models.CharField(max_length=20)),
                ('sedeInicial', models.CharField(max_length=20)),
                ('UsuarioFinal', models.CharField(max_length=20)),
                ('unidadOrganicaFinal', models.CharField(max_length=20)),
                ('sedeFinal', models.CharField(max_length=20)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bien')),
                ('detalleSalida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.detallesalida')),
                ('detalleTransferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.detalletransferencia')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.funcionario')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.proceso')),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='unidadOrganica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.unidadorganica'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=10)),
                ('contrasena', models.CharField(max_length=20)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.estado')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rol')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sede')),
                ('unidadOrganica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.unidadorganica')),
            ],
        ),
        migrations.AddField(
            model_name='proceso',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usuario'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='MOvUser_Product',
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
